baseURL = 'https://chacron.one/'
languageCode = 'en-us'
title = 'Chacron1'
theme = 'digio'
[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'blog'
    pageRef = '/blog'
    weight = 2
